// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: medi.proto

package medi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoctorAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Skill         string                 `protobuf:"bytes,3,opt,name=Skill,proto3" json:"Skill,omitempty"`
	DepartmentID  int64                  `protobuf:"varint,4,opt,name=DepartmentID,proto3" json:"DepartmentID,omitempty"`
	ServicePrice  float32                `protobuf:"fixed32,5,opt,name=ServicePrice,proto3" json:"ServicePrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorAddReq) Reset() {
	*x = DoctorAddReq{}
	mi := &file_medi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorAddReq) ProtoMessage() {}

func (x *DoctorAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_medi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorAddReq.ProtoReflect.Descriptor instead.
func (*DoctorAddReq) Descriptor() ([]byte, []int) {
	return file_medi_proto_rawDescGZIP(), []int{0}
}

func (x *DoctorAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DoctorAddReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DoctorAddReq) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *DoctorAddReq) GetDepartmentID() int64 {
	if x != nil {
		return x.DepartmentID
	}
	return 0
}

func (x *DoctorAddReq) GetServicePrice() float32 {
	if x != nil {
		return x.ServicePrice
	}
	return 0
}

type DoctorAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorAddResp) Reset() {
	*x = DoctorAddResp{}
	mi := &file_medi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorAddResp) ProtoMessage() {}

func (x *DoctorAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_medi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorAddResp.ProtoReflect.Descriptor instead.
func (*DoctorAddResp) Descriptor() ([]byte, []int) {
	return file_medi_proto_rawDescGZIP(), []int{1}
}

func (x *DoctorAddResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ScheduleAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientID     int64                  `protobuf:"varint,1,opt,name=PatientID,proto3" json:"PatientID,omitempty"`
	DoctorID      int64                  `protobuf:"varint,2,opt,name=DoctorID,proto3" json:"DoctorID,omitempty"`
	DepartmentID  int64                  `protobuf:"varint,3,opt,name=DepartmentID,proto3" json:"DepartmentID,omitempty"`
	ScheduleDate  string                 `protobuf:"bytes,4,opt,name=ScheduleDate,proto3" json:"ScheduleDate,omitempty"`
	ScheduleTime  string                 `protobuf:"bytes,5,opt,name=ScheduleTime,proto3" json:"ScheduleTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleAddReq) Reset() {
	*x = ScheduleAddReq{}
	mi := &file_medi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleAddReq) ProtoMessage() {}

func (x *ScheduleAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_medi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleAddReq.ProtoReflect.Descriptor instead.
func (*ScheduleAddReq) Descriptor() ([]byte, []int) {
	return file_medi_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduleAddReq) GetPatientID() int64 {
	if x != nil {
		return x.PatientID
	}
	return 0
}

func (x *ScheduleAddReq) GetDoctorID() int64 {
	if x != nil {
		return x.DoctorID
	}
	return 0
}

func (x *ScheduleAddReq) GetDepartmentID() int64 {
	if x != nil {
		return x.DepartmentID
	}
	return 0
}

func (x *ScheduleAddReq) GetScheduleDate() string {
	if x != nil {
		return x.ScheduleDate
	}
	return ""
}

func (x *ScheduleAddReq) GetScheduleTime() string {
	if x != nil {
		return x.ScheduleTime
	}
	return ""
}

type ScheduleAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleAddResp) Reset() {
	*x = ScheduleAddResp{}
	mi := &file_medi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleAddResp) ProtoMessage() {}

func (x *ScheduleAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_medi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleAddResp.ProtoReflect.Descriptor instead.
func (*ScheduleAddResp) Descriptor() ([]byte, []int) {
	return file_medi_proto_rawDescGZIP(), []int{3}
}

func (x *ScheduleAddResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DoctorListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorListReq) Reset() {
	*x = DoctorListReq{}
	mi := &file_medi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorListReq) ProtoMessage() {}

func (x *DoctorListReq) ProtoReflect() protoreflect.Message {
	mi := &file_medi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorListReq.ProtoReflect.Descriptor instead.
func (*DoctorListReq) Descriptor() ([]byte, []int) {
	return file_medi_proto_rawDescGZIP(), []int{4}
}

func (x *DoctorListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DoctorListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DoctorListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DoctorListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*DoctorListData      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorListResp) Reset() {
	*x = DoctorListResp{}
	mi := &file_medi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorListResp) ProtoMessage() {}

func (x *DoctorListResp) ProtoReflect() protoreflect.Message {
	mi := &file_medi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorListResp.ProtoReflect.Descriptor instead.
func (*DoctorListResp) Descriptor() ([]byte, []int) {
	return file_medi_proto_rawDescGZIP(), []int{5}
}

func (x *DoctorListResp) GetList() []*DoctorListData {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *DoctorListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DoctorListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Skill         string                 `protobuf:"bytes,3,opt,name=Skill,proto3" json:"Skill,omitempty"`
	DepartmentID  int64                  `protobuf:"varint,4,opt,name=DepartmentID,proto3" json:"DepartmentID,omitempty"`
	ServicePrice  float32                `protobuf:"fixed32,5,opt,name=ServicePrice,proto3" json:"ServicePrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorListData) Reset() {
	*x = DoctorListData{}
	mi := &file_medi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorListData) ProtoMessage() {}

func (x *DoctorListData) ProtoReflect() protoreflect.Message {
	mi := &file_medi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorListData.ProtoReflect.Descriptor instead.
func (*DoctorListData) Descriptor() ([]byte, []int) {
	return file_medi_proto_rawDescGZIP(), []int{6}
}

func (x *DoctorListData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DoctorListData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DoctorListData) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *DoctorListData) GetDepartmentID() int64 {
	if x != nil {
		return x.DepartmentID
	}
	return 0
}

func (x *DoctorListData) GetServicePrice() float32 {
	if x != nil {
		return x.ServicePrice
	}
	return 0
}

type AppointmentAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientID     int64                  `protobuf:"varint,1,opt,name=PatientID,proto3" json:"PatientID,omitempty"`
	DoctorID      int64                  `protobuf:"varint,2,opt,name=DoctorID,proto3" json:"DoctorID,omitempty"`
	DepartmentID  int64                  `protobuf:"varint,3,opt,name=DepartmentID,proto3" json:"DepartmentID,omitempty"`
	ScheduleID    int64                  `protobuf:"varint,4,opt,name=ScheduleID,proto3" json:"ScheduleID,omitempty"`
	ScheduleDate  string                 `protobuf:"bytes,5,opt,name=ScheduleDate,proto3" json:"ScheduleDate,omitempty"`
	ScheduleTime  string                 `protobuf:"bytes,6,opt,name=ScheduleTime,proto3" json:"ScheduleTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentAddReq) Reset() {
	*x = AppointmentAddReq{}
	mi := &file_medi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentAddReq) ProtoMessage() {}

func (x *AppointmentAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_medi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentAddReq.ProtoReflect.Descriptor instead.
func (*AppointmentAddReq) Descriptor() ([]byte, []int) {
	return file_medi_proto_rawDescGZIP(), []int{7}
}

func (x *AppointmentAddReq) GetPatientID() int64 {
	if x != nil {
		return x.PatientID
	}
	return 0
}

func (x *AppointmentAddReq) GetDoctorID() int64 {
	if x != nil {
		return x.DoctorID
	}
	return 0
}

func (x *AppointmentAddReq) GetDepartmentID() int64 {
	if x != nil {
		return x.DepartmentID
	}
	return 0
}

func (x *AppointmentAddReq) GetScheduleID() int64 {
	if x != nil {
		return x.ScheduleID
	}
	return 0
}

func (x *AppointmentAddReq) GetScheduleDate() string {
	if x != nil {
		return x.ScheduleDate
	}
	return ""
}

func (x *AppointmentAddReq) GetScheduleTime() string {
	if x != nil {
		return x.ScheduleTime
	}
	return ""
}

type AppointmentAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentNo string                 `protobuf:"bytes,1,opt,name=appointment_no,json=appointmentNo,proto3" json:"appointment_no,omitempty"`
	SeralNo       string                 `protobuf:"bytes,2,opt,name=seral_no,json=seralNo,proto3" json:"seral_no,omitempty"`
	PayUrl        string                 `protobuf:"bytes,3,opt,name=payUrl,proto3" json:"payUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentAddResp) Reset() {
	*x = AppointmentAddResp{}
	mi := &file_medi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentAddResp) ProtoMessage() {}

func (x *AppointmentAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_medi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentAddResp.ProtoReflect.Descriptor instead.
func (*AppointmentAddResp) Descriptor() ([]byte, []int) {
	return file_medi_proto_rawDescGZIP(), []int{8}
}

func (x *AppointmentAddResp) GetAppointmentNo() string {
	if x != nil {
		return x.AppointmentNo
	}
	return ""
}

func (x *AppointmentAddResp) GetSeralNo() string {
	if x != nil {
		return x.SeralNo
	}
	return ""
}

func (x *AppointmentAddResp) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

var File_medi_proto protoreflect.FileDescriptor

const file_medi_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"medi.proto\x12\x04medi\"\x96\x01\n" +
	"\fDoctorAddReq\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x14\n" +
	"\x05Skill\x18\x03 \x01(\tR\x05Skill\x12\"\n" +
	"\fDepartmentID\x18\x04 \x01(\x03R\fDepartmentID\x12\"\n" +
	"\fServicePrice\x18\x05 \x01(\x02R\fServicePrice\"\x1f\n" +
	"\rDoctorAddResp\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"\xb6\x01\n" +
	"\x0eScheduleAddReq\x12\x1c\n" +
	"\tPatientID\x18\x01 \x01(\x03R\tPatientID\x12\x1a\n" +
	"\bDoctorID\x18\x02 \x01(\x03R\bDoctorID\x12\"\n" +
	"\fDepartmentID\x18\x03 \x01(\x03R\fDepartmentID\x12\"\n" +
	"\fScheduleDate\x18\x04 \x01(\tR\fScheduleDate\x12\"\n" +
	"\fScheduleTime\x18\x05 \x01(\tR\fScheduleTime\"!\n" +
	"\x0fScheduleAddResp\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"K\n" +
	"\rDoctorListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"P\n" +
	"\x0eDoctorListResp\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.medi.DoctorListDataR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x98\x01\n" +
	"\x0eDoctorListData\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12\x14\n" +
	"\x05Skill\x18\x03 \x01(\tR\x05Skill\x12\"\n" +
	"\fDepartmentID\x18\x04 \x01(\x03R\fDepartmentID\x12\"\n" +
	"\fServicePrice\x18\x05 \x01(\x02R\fServicePrice\"\xd9\x01\n" +
	"\x11AppointmentAddReq\x12\x1c\n" +
	"\tPatientID\x18\x01 \x01(\x03R\tPatientID\x12\x1a\n" +
	"\bDoctorID\x18\x02 \x01(\x03R\bDoctorID\x12\"\n" +
	"\fDepartmentID\x18\x03 \x01(\x03R\fDepartmentID\x12\x1e\n" +
	"\n" +
	"ScheduleID\x18\x04 \x01(\x03R\n" +
	"ScheduleID\x12\"\n" +
	"\fScheduleDate\x18\x05 \x01(\tR\fScheduleDate\x12\"\n" +
	"\fScheduleTime\x18\x06 \x01(\tR\fScheduleTime\"n\n" +
	"\x12AppointmentAddResp\x12%\n" +
	"\x0eappointment_no\x18\x01 \x01(\tR\rappointmentNo\x12\x19\n" +
	"\bseral_no\x18\x02 \x01(\tR\aseralNo\x12\x16\n" +
	"\x06payUrl\x18\x03 \x01(\tR\x06payUrl2\xf6\x01\n" +
	"\x04Medi\x124\n" +
	"\tDoctorAdd\x12\x12.medi.DoctorAddReq\x1a\x13.medi.DoctorAddResp\x12:\n" +
	"\vScheduleAdd\x12\x14.medi.ScheduleAddReq\x1a\x15.medi.ScheduleAddResp\x127\n" +
	"\n" +
	"DoctorList\x12\x13.medi.DoctorListReq\x1a\x14.medi.DoctorListResp\x12C\n" +
	"\x0eAppointmentAdd\x12\x17.medi.AppointmentAddReq\x1a\x18.medi.AppointmentAddRespB\x13Z\x11./proto/medi/medib\x06proto3"

var (
	file_medi_proto_rawDescOnce sync.Once
	file_medi_proto_rawDescData []byte
)

func file_medi_proto_rawDescGZIP() []byte {
	file_medi_proto_rawDescOnce.Do(func() {
		file_medi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_medi_proto_rawDesc), len(file_medi_proto_rawDesc)))
	})
	return file_medi_proto_rawDescData
}

var file_medi_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_medi_proto_goTypes = []any{
	(*DoctorAddReq)(nil),       // 0: medi.DoctorAddReq
	(*DoctorAddResp)(nil),      // 1: medi.DoctorAddResp
	(*ScheduleAddReq)(nil),     // 2: medi.ScheduleAddReq
	(*ScheduleAddResp)(nil),    // 3: medi.ScheduleAddResp
	(*DoctorListReq)(nil),      // 4: medi.DoctorListReq
	(*DoctorListResp)(nil),     // 5: medi.DoctorListResp
	(*DoctorListData)(nil),     // 6: medi.DoctorListData
	(*AppointmentAddReq)(nil),  // 7: medi.AppointmentAddReq
	(*AppointmentAddResp)(nil), // 8: medi.AppointmentAddResp
}
var file_medi_proto_depIdxs = []int32{
	6, // 0: medi.DoctorListResp.list:type_name -> medi.DoctorListData
	0, // 1: medi.Medi.DoctorAdd:input_type -> medi.DoctorAddReq
	2, // 2: medi.Medi.ScheduleAdd:input_type -> medi.ScheduleAddReq
	4, // 3: medi.Medi.DoctorList:input_type -> medi.DoctorListReq
	7, // 4: medi.Medi.AppointmentAdd:input_type -> medi.AppointmentAddReq
	1, // 5: medi.Medi.DoctorAdd:output_type -> medi.DoctorAddResp
	3, // 6: medi.Medi.ScheduleAdd:output_type -> medi.ScheduleAddResp
	5, // 7: medi.Medi.DoctorList:output_type -> medi.DoctorListResp
	8, // 8: medi.Medi.AppointmentAdd:output_type -> medi.AppointmentAddResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_medi_proto_init() }
func file_medi_proto_init() {
	if File_medi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_medi_proto_rawDesc), len(file_medi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_medi_proto_goTypes,
		DependencyIndexes: file_medi_proto_depIdxs,
		MessageInfos:      file_medi_proto_msgTypes,
	}.Build()
	File_medi_proto = out.File
	file_medi_proto_goTypes = nil
	file_medi_proto_depIdxs = nil
}
