// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: medi.proto

package medi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Medi_DoctorAdd_FullMethodName      = "/medi.Medi/DoctorAdd"
	Medi_ScheduleAdd_FullMethodName    = "/medi.Medi/ScheduleAdd"
	Medi_DoctorList_FullMethodName     = "/medi.Medi/DoctorList"
	Medi_AppointmentAdd_FullMethodName = "/medi.Medi/AppointmentAdd"
)

// MediClient is the client API for Medi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediClient interface {
	DoctorAdd(ctx context.Context, in *DoctorAddReq, opts ...grpc.CallOption) (*DoctorAddResp, error)
	ScheduleAdd(ctx context.Context, in *ScheduleAddReq, opts ...grpc.CallOption) (*ScheduleAddResp, error)
	DoctorList(ctx context.Context, in *DoctorListReq, opts ...grpc.CallOption) (*DoctorListResp, error)
	AppointmentAdd(ctx context.Context, in *AppointmentAddReq, opts ...grpc.CallOption) (*AppointmentAddResp, error)
}

type mediClient struct {
	cc grpc.ClientConnInterface
}

func NewMediClient(cc grpc.ClientConnInterface) MediClient {
	return &mediClient{cc}
}

func (c *mediClient) DoctorAdd(ctx context.Context, in *DoctorAddReq, opts ...grpc.CallOption) (*DoctorAddResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoctorAddResp)
	err := c.cc.Invoke(ctx, Medi_DoctorAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediClient) ScheduleAdd(ctx context.Context, in *ScheduleAddReq, opts ...grpc.CallOption) (*ScheduleAddResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleAddResp)
	err := c.cc.Invoke(ctx, Medi_ScheduleAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediClient) DoctorList(ctx context.Context, in *DoctorListReq, opts ...grpc.CallOption) (*DoctorListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoctorListResp)
	err := c.cc.Invoke(ctx, Medi_DoctorList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediClient) AppointmentAdd(ctx context.Context, in *AppointmentAddReq, opts ...grpc.CallOption) (*AppointmentAddResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppointmentAddResp)
	err := c.cc.Invoke(ctx, Medi_AppointmentAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediServer is the server API for Medi service.
// All implementations must embed UnimplementedMediServer
// for forward compatibility.
type MediServer interface {
	DoctorAdd(context.Context, *DoctorAddReq) (*DoctorAddResp, error)
	ScheduleAdd(context.Context, *ScheduleAddReq) (*ScheduleAddResp, error)
	DoctorList(context.Context, *DoctorListReq) (*DoctorListResp, error)
	AppointmentAdd(context.Context, *AppointmentAddReq) (*AppointmentAddResp, error)
	mustEmbedUnimplementedMediServer()
}

// UnimplementedMediServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediServer struct{}

func (UnimplementedMediServer) DoctorAdd(context.Context, *DoctorAddReq) (*DoctorAddResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DoctorAdd not implemented")
}
func (UnimplementedMediServer) ScheduleAdd(context.Context, *ScheduleAddReq) (*ScheduleAddResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleAdd not implemented")
}
func (UnimplementedMediServer) DoctorList(context.Context, *DoctorListReq) (*DoctorListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DoctorList not implemented")
}
func (UnimplementedMediServer) AppointmentAdd(context.Context, *AppointmentAddReq) (*AppointmentAddResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AppointmentAdd not implemented")
}
func (UnimplementedMediServer) mustEmbedUnimplementedMediServer() {}
func (UnimplementedMediServer) testEmbeddedByValue()              {}

// UnsafeMediServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediServer will
// result in compilation errors.
type UnsafeMediServer interface {
	mustEmbedUnimplementedMediServer()
}

func RegisterMediServer(s grpc.ServiceRegistrar, srv MediServer) {
	// If the following call panics, it indicates UnimplementedMediServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Medi_ServiceDesc, srv)
}

func _Medi_DoctorAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoctorAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediServer).DoctorAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Medi_DoctorAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediServer).DoctorAdd(ctx, req.(*DoctorAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Medi_ScheduleAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediServer).ScheduleAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Medi_ScheduleAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediServer).ScheduleAdd(ctx, req.(*ScheduleAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Medi_DoctorList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoctorListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediServer).DoctorList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Medi_DoctorList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediServer).DoctorList(ctx, req.(*DoctorListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Medi_AppointmentAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppointmentAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediServer).AppointmentAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Medi_AppointmentAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediServer).AppointmentAdd(ctx, req.(*AppointmentAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Medi_ServiceDesc is the grpc.ServiceDesc for Medi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Medi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "medi.Medi",
	HandlerType: (*MediServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoctorAdd",
			Handler:    _Medi_DoctorAdd_Handler,
		},
		{
			MethodName: "ScheduleAdd",
			Handler:    _Medi_ScheduleAdd_Handler,
		},
		{
			MethodName: "DoctorList",
			Handler:    _Medi_DoctorList_Handler,
		},
		{
			MethodName: "AppointmentAdd",
			Handler:    _Medi_AppointmentAdd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "medi.proto",
}
